# Site settings
title: "Open Blaaast"
name: "Blaaast"
description: "Digital communication · Paris"
email: tom@blaaast.co
author: "Tom Coquereau and Sofian Meguellati"
baseurl: ""
url: "http://open.blaaast.co"
google_analytics: UA-45409833-1

twitter: goblaaast

# Build settings
markdown: kramdown
permalink: /:year/:month/:title
paginate: 3
